{{- if .Capabilities.APIVersions.Has "security.openshift.io/v1" }}
{{- if .Values.modelServiceAccount.create -}}
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: kubeai-models
allowPrivilegeEscalation: false
readOnlyRootFilesystem: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
seccompProfiles:
  - runtime/default
requiredDropCapabilities:
  - ALL
users:
  - system:serviceaccount:{{ .Release.Namespace }}:{{ include "models.serviceAccountName" . }}
{{- end }}
{{- end }}
